import json


def find_node(parent_node, path_elements):
    next_step = path_elements.pop(0)
    for child_node in parent_node['children']:
        if (child_node['name'] == next_step):
            if (len(child_node['children']) > 0):
                return find_node(child_node, path_elements)
            else:
                return child_node
    return None


if __name__ == "__main__":

    # Load SonarCube JSON file, generated by CodeCharta import
    data = None
    with open('/tmp/sonar.json') as json_file:
        data = json.load(json_file)
    project_root = data['nodes'][0]['children'][0]['children'][0]
    project_root['name'] = ""

    # Enrich data
    file_name = "user-interface/src/main/java/ksch/registration/EditPatientDetailsActivity.java"
    file_attributes = find_node(project_root, file_name.split("/"))['attributes']
    file_attributes['xxxx'] = 42

    # Write out modified JSON file
    with open('/tmp/sonar.json', 'w') as outfile:
        json.dump(data, outfile)
